### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by andiikaa** [IoTUDresden/proteus#5]
There should be a REST API for PROtEUS, to access at least the important functions like:

- list processes
  - running
  - executable
  - finished
  - failed
- start processes

Or would it be better, to expose the complete API via REST, including state changes and deployment?

**Comment by ronsei** [comment]
Yes, deployment of processes should also be possible (upload and download of models and their deployment as well as execution). State Changes are not necessary yet, but probably interesting for future use cases. The optimal solution would be to expose the complete API via REST (is implementing the server interface enough?) For now we can skip the pub/sub functionality though. Getting the state of an instance (including active process steps) via an active REST call would also be useful.
